Dz 2
EgorKekor/C_HomeWorks pull request #3
Opened 2019-03-23 14:18 UTC by EgorKekor

2019-03-25 10:34 UTC, o2gy84 requested changes

2019-03-25 10:34 UTC, o2gy84 commented on dz2/main.c
> +    stack->data[stack->size] = value;
плохо что нет проверки на переплонение

2019-03-25 10:34 UTC, o2gy84 commented on dz2/main.c
> +        return NULL;
тут утечка, надо освобождать arr

2019-03-25 10:34 UTC, o2gy84 commented on dz2/main.c
> +    if ((polish = (char*)calloc(51, sizeof(char))) == NULL) {
что за 51 ???

2019-03-25 10:34 UTC, o2gy84 commented on dz2/main.c
> +    int digits[20];
что за 20 ???

2019-03-25 10:35 UTC, o2gy84 commented
Пока ставлю 10 баллов. Кроме перечисленных моментов еще не очень хорошо, что стек не динамический, а с заранее заданным размером.
Можно исправить стек и замечания, снова запросить ревью и буду увеличвать оценку.

2019-03-25 14:45 UTC, EgorKekor commented
Там где с утечкой, все так и планировалось, передать ей адрес по которому
расширить, а если не расширилось, то вернуть null, и уже там освободить,
ведь я присваиваю новую память переменной timeless, а arr останется не
увеличенным и валидным

пн, 25 мар. 2019 г., 13:34 Victor Mogilin notifications@github.com:

> *@o2gy84* requested changes on this pull request.
> ------------------------------
>
> In dz2/main.c
> <https://github.com/EgorKekor/C_HomeWorks/pull/3#discussion_r268568781>:
>
> > +
>
> +typedef struct varriable {
>
> +    char *name;
>
> +    Bool value;
>
> +    size_t len;
>
> +} var;
>
> +
>
> +typedef struct Stack {
>
> +    char data[STACK_SIZE];
>
> +    size_t size;
>
> +}Stack;
>
> +
>
> +// ================================
>
> +
>
> +void push(Stack *stack, const char value) {
>
> +    stack->data[stack->size] = value;
>
>
> плохо что нет проверки на переплонение
> ------------------------------
>
> In dz2/main.c
> <https://github.com/EgorKekor/C_HomeWorks/pull/3#discussion_r268569373>:
>
> > +    size_t start = *ind;
>
> +    char last = -1;
>
> +    while ((last = pop(stack)) != -1) {
>
> +        polish[*ind] = last;
>
> +        *ind = *ind + 1;
>
> +    }
>
> +    polish[*ind] = '\0';
>
> +    return (*ind - start);
>
> +}
>
> +
>
> +// ================================================================
>
> +
>
> +char *increase_string(char* arr, size_t new_len) {
>
> +    char *timeless = NULL;
>
> +    if ((timeless = (char*)realloc(arr, new_len * sizeof(char))) == NULL) {
>
> +        return NULL;
>
>
> тут утечка, надо освобождать arr
> ------------------------------
>
> In dz2/main.c
> <https://github.com/EgorKekor/C_HomeWorks/pull/3#discussion_r268574250>:
>
> > +    switch (ch) {
>
> +        case '(': return 0;
>
> +        case ')': return 0;
>
> +        case 'o': return 1;     //  or
>
> +        case 'x': return 1;     //  xor
>
> +        case 'a': return 2;     //  and
>
> +        case 'n': return 3;     //  not
>
> +        default: return 0;
>
> +    }
>
> +}
>
> +
>
> +// ================================
>
> +
>
> +char* get_polish(char* expr) {
>
> +    char* polish = NULL;
>
> +    if ((polish = (char*)calloc(51, sizeof(char))) == NULL) {
>
>
> что за 51 ???
> ------------------------------
>
> In dz2/main.c
> <https://github.com/EgorKekor/C_HomeWorks/pull/3#discussion_r268574776>:
>
> > +                    push(&operators, expr[i]);
>
> +                    polish[p++] = last;
>
> +                }
>
> +            }
>
> +        }
>
> +        i++;
>
> +        polish[p] = '\0';
>
> +    }
>
> +    pop_all(&operators, polish, &p);
>
> +    return polish;
>
> +}
>
> +
>
> +// ================================
>
> +
>
> +int calculate(char* polish) {
>
> +    int digits[20];
>
>
> что за 20 ???
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/EgorKekor/C_HomeWorks/pull/3#pullrequestreview-218241410>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AuFniMCm9jDEgEqaZW_iQcamUEtZ17HDks5vaKY7gaJpZM4cE8Cb>
> .
>

2019-04-06 19:29 UTC, o2gy84 approved these changes
в принципе все ок, ставлю 14 баллов из 15

2019-04-06 19:29 UTC, o2gy84 commented on dz2/main.c
> +    int digits[max_operands];
не стандартное расширение С++. 
не все компиляторы поддерживают эту фичу - создание массива, длина которого вычисляется в ранитайме, т.е. прямо во время выполнения программы

2019-04-06 19:29 UTC, merged